# 워크플로의 이름 지정
name: CI/CD

# 워크플로가 시작될 조건 지정
on:
  pull_request: # pull request 생성 및 업데이트 시 실행
    branches: [ master ] # 자신의 branch에 맞게 설정 (main으로 되어있을 수도 있음.)


jobs:
  test:
    build:
      runs-on: ubuntu-latest # 실행 환경 지정

      # 실행 스텝 지정
      steps:
        - uses: mirromutth/mysql-action@v1.1
          with:
            container port: 3306
            mysql database: quizboard
            mysql user: quizboard
            mysql password: ${{ secrets.DatabasePassword }}

        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew # gradlew 파일에 실행 권한을 부여

        - name: Build with Gradle
          env: # MySQL에 연결하도록 환경 변수 전달
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/quizboard
            SPRING_DATASOURCE_USERNAME: quizboard
            SPRING_DATASOURCE_PASSWORD: ${{ secrets.DatabasePassword }}
          run: ./gradlew clean build # 빌드 이전 상태로 돌리고 다시 빌드 명령어