# 워크플로의 이름 지정
name: CI/CD

# 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ master ] # 자신의 branch에 맞게 설정 (main으로 되어있을 수도 있음.)

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          # MySQL 컨테이너가 제대로 시작되었는지 확인

    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # gradlew 파일에 실행 권한을 부여

      - name: Build with Gradle
        env: # MySQL에 연결하도록 환경 변수 전달
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{ secrets.MYSQL_DATABASE }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: ./gradlew clean build # 빌드 이전 상태로 돌리고 다시 빌드 명령어